import { Header } from '@/components/header'
import type { Metadata } from 'next'
import { Saira } from 'next/font/google'
import { DefaultProvider } from '@/components/default-providers'
import './globals.css'

const saira = Saira({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600'],
})

export const metadata: Metadata = {
  title: 'Create Next Ap ',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body className={saira.className}>
        <DefaultProvider>
          <Header />
          {children}
        </DefaultProvider>
      </body>
    </html>
  )
}
